### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by lottithethief** [chingu-voyages/v35-toucans-team-03#20]
As a user, 
I want to have a basic webpage
so that I can access and navigate through all of the different areas.  

Tasks
- [x] Create a blank webpage
- [x] Create index page / folder for everyone to access the code
- [x] Decide group Netlify account or solo Netlify account, see comment.

**Comment by lottithethief** [comment]
Do we need to create free, shared Netlify group account so that everyone can access and deploy from it? To be discussed in Team and with Jim in office hour.

**Comment by Marrockx** [comment]
done and deployed
