### ISSUE TITLE
Create UX Design 

### ISSUE THREAD

**Issue by lottithethief** [chingu-voyages/v35-toucans-team-03#22]
- [x] Create low fidelity design in Figma for website

**Comment by Marrockx** [comment]
The Homepage design is complete. Done by @Marrockx  and @DEVOPEOLUWA

**Comment by Marrockx** [comment]
- [Figma design link](https://www.figma.com/file/bPQ4HsVOXgMI9xr29lNIQw/Design-Mockup?node-id=4%3A4)

- [Fig Jam Board](https://www.figma.com/file/19Vcme36TnljBwmb4dYPqq/Mental-Score-Features?node-id=0%3A1) - Planning before the design
