### ISSUE TITLE
Building the Basic Webpage

### ISSUE THREAD

**Issue by lottithethief** [chingu-voyages/v35-toucans-team-03#28]
As a user, I want to access the website, to see what Compass is all about. 

Tasks
- [x] Deploy blank webpage so that everyone can access it
- [x]  Build the basic webpage with the main body structure, home page link and the logo/name (just create the basics, the navigation, responsive design and more complex features will follow in later sprints). 
- [x] Add button for alcohol consumption assessment

**Comment by Marrockx** [comment]
This is now complete
